# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - proftaak-sso

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://proftaak2.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_0bf49bb8d8624597944a7eea5118acb0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3f512e100bd94e9db3e745d3d05224d9 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: proftaak2.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0bf49bb8d8624597944a7eea5118acb0 }}/sso:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'proftaak-sso'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_23a363d691a84cc89c3cd36fc9703480 }}
        images: 'proftaak2.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0bf49bb8d8624597944a7eea5118acb0 }}/sso:${{ github.sha }}'